### ISSUE TITLE
V6 Using Paper overrides style of unrelated components

### ISSUE THREAD

**Issue by gaetansnl** [mui/pigment-css#205]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/devbox/peaceful-estrela-forked-94sr78

### Current behavior

App bar isn't blue

### Expected behavior

App bar is blue

### Context

When there is a paper component in the page, the paper css conflict

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: v6 paper

**Search keywords**:

**Comment by siriwatknp** [comment]
Found the root cause, it happens because the order of the stylesheets (page.css comes after layout.css).

The **layout.css** includes AppBar + Paper stylesheet because Paper is a dependency of AppBar.

The **page.css** includes Paper stylesheet because of the import.

Since both files contain the same stylesheet, it depends on the order between them.

https://github.com/user-attachments/assets/9f178621-73d6-4e9b-bee9-686cafcd0e60

I think this is a caching bug in Pigment CSS.

**Comment by corydeppen** [comment]
This sounds similar to what I'm seeing in #199.

**Comment by aarongarciah** [comment]
@corydeppen yes, looks like the same issue.

**Comment by siriwatknp** [comment]
duplicate #199
