### ISSUE TITLE
[docs] Documentation feedback on how to use pigment-css with @mui/material and more

### ISSUE THREAD

**Issue by kdichev** [mui/pigment-css#247]
### Search keywords

docs, getting started, migrating to

### Related page

https://mui.com/material-ui/migration/migrating-to-pigment-css/#installation, https://mui.com/material-ui/experimental-api/pigment-css/#manual-installation

### Kind of issue

Unclear explanations

### Issue description

Over the past day, I've been working on integrating @mui/material with pigment-css and encountered some issues navigating the documentation. The two pages that led to confusion were:

[Migrating to Pigment CSS](https://mui.com/material-ui/migration/migrating-to-pigment-css/#introduction)
[Getting started with Pigment CSS](https://mui.com/material-ui/experimental-api/pigment-css/#manual-installation)

To help others avoid these issues, I consolidated my findings in this [repository](https://github.com/kdichev/mui-pigment-css). I've also implemented the Getting Started guide in [this pull request](https://github.com/kdichev/mui-pigment-css/pull/2) and the Migrating to Pigment CSS guide in [this pull request](https://github.com/kdichev/mui-pigment-css/pull/3).

Additionally, I highlighted several points in the documentation that could be clarified, including a few errors (like the syntax error in the Getting Started section).

### Context

I was trying to implement `pigment-css` with `@mui/material`

**Comment by aarongarciah** [comment]
Thanks for the feedback @kdichev. We are aware of the current documentation not being ideal (e.g. Pigment CSS not having proper docs and https://mui.com/material-ui/experimental-api/pigment-css/ living in the Material UI docs). Note that the installation instructions are a bit different between https://github.com/mui/pigment-css and https://github.com/mui/material-ui because for the later we offer an adapter package (`@mui/material-pigment-css`).

From the issue description, it's not 100% clear what would be your expectation. Would you mind opening the corresponding PRs with the improvements you think we need to make in the relevant repositories? Namely https://github.com/mui/pigment-css and https://github.com/mui/material-ui.
